WebBanHang/WebBanHang/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHang.Context;
using PagedList.Mvc;
using PagedList;

namespace WebBanHang.Controllers
{
    public class CategoryController : Controller
    {
        // GET: Category
        TNSTOREEntities objTNSTOREEntities = new TNSTOREEntities();
        public ActionResult Index()
        {
            var lstringCategory = objTNSTOREEntities.Categories.ToList();
            return View(lstringCategory);
        }
        public ActionResult CategoryProduct(int Id, int? page)
        {
            Category obj = new Category();
            var lstCateProduct = objTNSTOREEntities.Products.Where(n => n.CategoryId == Id).ToList();
            int pagesize = 4;
            int PageNumber = (page ?? 1);
            ViewBag.Count = lstCateProduct.Count;
            return View(lstCateProduct.ToPagedList(PageNumber, pagesize));
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (objTNSTOREEntities != null)

                    objTNSTOREEntities.Dispose();
                objTNSTOREEntities.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebBanHang/WebBanHang/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHang.Context;

namespace WebBanHang.Controllers
{
    public class CommentController : Controller
    {
        TNSTOREEntities objTNStoreEntity = new TNSTOREEntities();
        // GET: Comment
        [HttpGet]
        public ActionResult Index()
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                return View();
            }
        }
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Index(Comment comment)
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            else
            { 
                comment.IdUser = int.Parse(Session["Id"].ToString());
                comment.Day = DateTime.Now;
                objTNStoreEntity.Comments.Add(comment);
                objTNStoreEntity.SaveChanges();
                return RedirectToAction("Index","Home");
              
            }
     
              
        }
        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        if (objTNStoreEntity != null)

        //            objTNStoreEntity.Dispose();
        //        objTNStoreEntity.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

WebBanHang/WebBanHang/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHang.Context;

namespace WebBanHang.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        TNSTOREEntities objTNStoreEntity = new TNSTOREEntities();
        public ActionResult Details(int Id)
        {
            var objProduct = objTNStoreEntity.Products.Where(n => n.Id == Id).FirstOrDefault();
            return View(objProduct);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (objTNStoreEntity != null)

                    objTNStoreEntity.Dispose();
                objTNStoreEntity.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebBanHang/WebBanHang/Views/Category/CategoryProduct.cshtml
@model IPagedList<WebBanHang.Context.Product>
@using PagedList;
@using PagedList.Mvc;
@{
    ViewBag.Title = "CategoryProduct";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

    <section class="section-content padding-y">
        <div class="container">
            <div class="card mb-3">
                <div class="card-body">
                    <ol class="breadcrumb float-left">
                       
                        <li class="breadcrumb-item active"> Có @ViewBag.Count sản phẩm </li>
                    </ol>
                </div> <!-- card-body .// -->
            </div> <!-- card.// -->
            <!-- ============================ FILTER TOP END.// ================================= -->


            <div class="row">
                <aside class="col-md-2">

                </aside> <!-- col.// -->
                <main class="col-md-10">


                    <header class="mb-3">
                    </header><!-- sect-heading -->
                    @foreach (var item in Model)
                    {
                        <article class="card card-product-list">
                            <div class="row no-gutters">
                                <aside class="col-md-3">
                                    <a href="@Url.Action("Details", "Product", new { Id = item.Id})" class="img-wrap">
                                        <span class="badge badge-danger"> NEW </span>
                                        <img src="~/Content/images/items/@item.Avater">
                                    </a>
                                </aside> <!-- col.// -->
                                <div class="col-md-6">
                                    <div class="info-main">
                                        <a href="#" class="h5 title"> @item.Name</a>
                                        <div class="rating-wrap mb-2">
                                            <ul class="rating-stars">
                                                <li style="width:100%" class="stars-active">
                                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </li>
                                                <li>
                                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </li>
                                            </ul>
                                            <div class="label-rating">9/10</div>
                                        </div> <!-- rating-wrap.// -->

                                        <p class="mb-3">
                                            <span class="tag"> <i class="fa fa-check"></i> Verified</span>
                                            <span class="tag"> @item.Year </span>
                                            <span class="tag"> @item.CPU Viewer </span>
                                            <span class="tag"> @item.OS </span>
                                        </p>

                                        <p>
                                            @Html.Raw(item.FullDescription)
                                        </p>
                                        <br />
                                        <small>
                                            @Html.Raw(item.ShortDes)
                                        </small>

                                    </div> <!-- info-main.// -->
                                </div> <!-- col.// -->
                                <aside class="col-sm-3">
                                    <div class="info-aside">
                                        <div class="price-wrap">
                                            <span class="h5 price">Khuyến mãi @item.PriceDiscount</span>
                                        </div> <!-- price-wrap.// -->
                                        <small class="text-warning">@item.Price VND</small>
                                    <br />
                                        <small class="text-warning">@item.RAM GB</small>

                                        <p class="text-muted mt-3">@item.Resolution inches</p>


                                    </div> <!-- info-aside.// -->
                                </aside> <!-- col.// -->
                            </div> <!-- row.// -->
                        </article> <!-- card-product .// -->
                    }
                    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
                    @Html.PagedListPager(Model, page => Url.Action("CategoryProduct", new { page, currentFilter = ViewBag.currentFilter }))


                </main> <!-- col.// -->

            </div>

        </div> <!-- container .//  -->
    </section>
    <section class="padding-y-lg bg-light border-top">
        <div class="container">

            <p class="pb-2 text-center">Phản hồi với tôi</p>

            <div class="row justify-content-md-center">
                <div class="col-lg-4 col-sm-6">

                    <div class="btn btn-block btn-warning"> <i class="fa fa-envelope"></i><a href="@Url.Action("Index","Comment")">Tại đây</a></div>
                    <small class="form-text">Chúng tôi sẽ cố gắng phản hồi lại bạn sớm nhất</small>
                </div> <!-- col-md-6.// -->
            </div>


        </div>
    </section>
  

WebBanHang/WebBanHang/Views/Category/Index.cshtml
@model List<WebBanHang.Context.Category>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="py-3 bg-light">
    <div class="container">
        <ol class="breadcrumb">
            @*<li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Trang chủ</a></li>*@
        </ol>
    </div>
</section>
<section class="section-content padding-y">
    <div class="container">

        <nav class="row">

            @foreach (var item in Model)
            {
            <div class="col-md-3">
               
                    <div class="card card-category">
                        <div class="img-wrap" style="background: #ffd7d7">
                            <img src="~/Content/images/items/@item.Avatar">
                        </div>
                        <div class="card-body">
                            <h4 class="card-title"><a href="#">@item.Name</a></h4>
                        </div>
                    </div>
   
            </div> <!-- col.// -->
            }
        </nav> <!-- row.// -->


    </div> <!-- container .//  -->
</section>