WebBanHang/WebBanHang/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHang.Context;
using WebBanHang.Models;

namespace WebBanHang.Controllers
{
    public class CartController : Controller
    {
        TNSTOREEntities objTNStoreEntity = new TNSTOREEntities();
       
        // GET: Cart
        public ActionResult Index()
        {
           
            return View((List<CartModel>)Session["cart"]);
        }
        public ActionResult AddToCart(int id, int Quantity)
        {
         
            if (Session["cart"] == null)
            {
                List<CartModel> cart = new List<CartModel>();
                cart.Add(new CartModel { Product = objTNStoreEntity.Products.Find(id), Quantity = Quantity});
                Session["cart"] = cart;
                Session["count"] = 1;        
            }
            else
            {
                List<CartModel> cart = (List<CartModel>)Session["cart"];
                //kiểm tra sản phẩm có tồn tại trong giỏ hàng chưa???
                int index = isExist(id);
                if (index != -1)
                {
                    //nếu sp tồn tại trong giỏ hàng thì cộng thêm số lượng
                    cart[index].Quantity += Quantity;
                   
                }
                else
                {
                    //nếu không tồn tại thì thêm sản phẩm vào giỏ hàng
                    cart.Add(new CartModel { Product = objTNStoreEntity.Products.Find(id), Quantity = Quantity });
                    //Tính lại số sản phẩm trong giỏ hàng
                    Session["count"] = Convert.ToInt32(Session["count"]) + 1;
         
                }
                Session["cart"] = cart;
            
            }
          var lst = objTNStoreEntity.Products.Where(n => n.Id == id).ToList();
          
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }
        private int isExist(int id)
        {
            List<CartModel> cart = (List<CartModel>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].Product.Id.Equals(id))
                    return i;
            return -1;
        }
        public ActionResult Remove(int Id)
        {
            List<CartModel> li = (List<CartModel>)Session["cart"];
            li.RemoveAll(x => x.Product.Id == Id);
            Session["cart"] = li;
            Session["count"] = Convert.ToInt32(Session["count"]) - 1;
            //return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (objTNStoreEntity != null)

                    objTNStoreEntity.Dispose();
                objTNStoreEntity.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebBanHang/WebBanHang/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHang.Context;
using PagedList.Mvc;
using PagedList;

namespace WebBanHang.Controllers
{
    public class CategoryController : Controller
    {
        // GET: Category
        TNSTOREEntities objTNSTOREEntities = new TNSTOREEntities();
        public ActionResult Index()
        {
            var lstringCategory = objTNSTOREEntities.Categories.ToList();
            return View(lstringCategory);
        }
        public ActionResult CategoryProduct(int Id, int? page)
        {
            Category obj = new Category();
            var lstCateProduct = objTNSTOREEntities.Products.Where(n => n.CategoryId == Id).ToList();
            int pagesize = 4;
            int PageNumber = (page ?? 1);
            ViewBag.Count = lstCateProduct.Count;
            return View(lstCateProduct.ToPagedList(PageNumber, pagesize));
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (objTNSTOREEntities != null)

                    objTNSTOREEntities.Dispose();
                objTNSTOREEntities.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebBanHang/WebBanHang/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHang.Context;

namespace WebBanHang.Controllers
{
    public class CommentController : Controller
    {
        TNSTOREEntities objTNStoreEntity = new TNSTOREEntities();
        // GET: Comment
        [HttpGet]
        public ActionResult Index()
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                return View();
            }
        }
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Index(Comment comment)
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            else
            { 
                comment.IdUser = int.Parse(Session["Id"].ToString());
                comment.Day = DateTime.Now;
                objTNStoreEntity.Comments.Add(comment);
                objTNStoreEntity.SaveChanges();
                return RedirectToAction("Index","Home");
              
            }
     
              
        }
        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        if (objTNStoreEntity != null)

        //            objTNStoreEntity.Dispose();
        //        objTNStoreEntity.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

WebBanHang/WebBanHang/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHang.Context;
using System.Security.Cryptography;
using System.Text;

namespace WebBanHang.Controllers
{
    public class UserController : Controller
    {
        TNSTOREEntities db = new TNSTOREEntities();

        // GET: User
        [HttpGet]
        public ActionResult Index()
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                int id = int.Parse(Session["Id"].ToString());
                var user = db.Users.Where(a => a.Id == id).FirstOrDefault();
                return View(user);
            }
        }
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Index(User user)
        {
             user.Id = (int)Session["Id"];
            
             db.Entry(user).State = System.Data.Entity.EntityState.Modified;
            user.PassWord = GetMD5(user.PassWord);
             db.SaveChanges();
            return RedirectToAction("Login", "Home");
        }
        public static string GetMD5(string str)
        {
            MD5 md5 = new MD5CryptoServiceProvider();
            byte[] fromData = Encoding.UTF8.GetBytes(str);
            byte[] targetData = md5.ComputeHash(fromData);
            string byte2String = null;

            for (int i = 0; i < targetData.Length; i++)
            {
                byte2String += targetData[i].ToString("x2");

            }
            return byte2String;
        }
    }
}

WebBanHang/WebBanHang/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="pragma" content="no-cache" />
    <meta http-equiv="cache-control" content="max-age=604800" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>TN STRORE</title>

    <link href="~/Content/images/favicon.ico" rel="shortcut icon" type="image/x-icon">

    <!-- jQuery -->
    <script src="~/Scripts/js/jquery-2.0.0.min.js" type="text/javascript"></script>
    <!-- Bootstrap4 files-->
    <script src="~/Scripts/js/bootstrap.bundle.min.js" type="text/javascript"></script>
    <link href="~/Content/css/bootstrap.css" rel="stylesheet" type="text/css" />

    <!-- Font awesome 5 -->
    <link href="~/Content/fonts/fontawesome/css/all.min.css" type="text/css" rel="stylesheet">

    <!-- custom style -->
    <link href="~/Content/css/ui.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/css/responsive.css" rel="stylesheet" type="text/css" />

    <!-- custom javascript -->
    <script src="~/Content/js/script.js" type="text/javascript"></script>
</head>
<body>

    <header class="section-header">
        <section class="header-main border-bottom">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-xl-2 col-lg-3 col-md-12">
                        <a href="#" class="brand-wrap">
                            <img class="logo" src="~/Content/images/logo.jpg">
                        </a> <!-- brand-wrap.// -->
                    </div>
                    <div class="col-xl-6 col-lg-5 col-md-6">
                        <form action="/TimKiem/Search" method="post" class="search-header">
                            <div class="input-group w-100">

                                @Html.TextBox("SearchString", "", htmlAttributes: new { @class = "form-control", placeholder = "Tìm kiếm" })

                                <div class="input-group-append">
                                    <button class="btn btn-facebook" type="submit">
                                        <i class="fa fa-search"></i> Tìm kiếm
                                    </button>
                                </div>
                            </div>
                        </form> <!-- search-wrap .end// -->
                    </div> <!-- col.// -->
                    <div class="col-xl-4 col-lg-4 col-md-6">
                        <div class="widgets-wrap float-md-right">
                            <div class="widget-header mr-3">
                              
                                    <div class="icon-area">
                                        <i class="fa fa-user"></i>
                                      
                                        <hr />
                                    </div>
                                    @if (Session["Id"] != null)
                                    {
                                        if (Session["isAdmin"] == null || Session["isAdmin"].Equals(false))
                                        {
                                         <a href="~/Home/Login">@Session["FullName"]</a> 
                                         }
                                         else
                                         {
                                             <a href="~/Admin/Product/Index"> Admin</a> 
                                         }
                                            <a href="~/Home/Logout"> Logout</a> 
                                            }

                                        else
                                            {
                                            <a href="~/Home/Register">Đăng kí</a>
                                            }
                          
                            </div>
                            <div class="widget-header mr-3">
                                <a href="@Url.Action("Index","Messenger")" class="widget-view">
                                    <div class="icon-area">
                                        <i class="fa fa-comment-dots"></i>
                                    </div>
                                    <small class="text"> Message </small>
                                </a>
                            </div>
                            @*<div class="widget-header mr-3">
                                    <a href="#" class="widget-view">
                                        <div class="icon-area">
                                            <i class="fa fa-store"></i>
                                        </div>
                                        <small class="text"> Đặt Hàng </small>
                                    </a>
                                </div>*@
                            <div class="widget-header">
                                <a href="@Url.Action("Index", "Cart")" class="widget-view">
                                    <div class="icon-area">
                                        <i class="fa fa-shopping-cart"></i>
                                        <span class="notify" id="CartCount">@Session["count"]</span>
                                    </div>
                                    <small class="text"> Giỏ Hàng </small>
                                </a>
                            </div>
                        </div> <!-- widgets-wrap.// -->
                    </div> <!-- col.// -->
                </div> <!-- row.// -->
            </div> <!-- container.// -->
        </section> <!-- header-main .// -->


        <nav class="navbar navbar-main navbar-expand-lg border-bottom">
            <div class="container">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main_nav" aria-controls="main_nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="main_nav">
                    <ul class="navbar-nav">
                        <li class="nav-item ">
                            <a class="nav-link " href="@Url.Action("Index", "Home")">Trang chủ </a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link " href="@Url.Action("Index", "Category")"> Loại Sản Phẩm </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index","TinhTrangGiaoHang")">Tình Trạng Giao Hàng</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "Comment")">Liên Hệ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "User")">Tài Khoản</a>
                        </li>

                    </ul>

                </div> <!-- collapse .// -->
            </div> <!-- container .// -->
        </nav>
    </header> <!-- section-header.// -->
    @RenderBody()


    <!-- ========================= SECTION SUBSCRIBE END// ========================= -->
    <!-- ========================= FOOTER ========================= -->
    <footer class="section-footer bg-secondary">
        <div class="container">
            <section class="footer-top padding-y-lg text-white">
                <div class="row">
                    <aside class="col-md col-6">
                        <h6 class="title">Nhãn Hàng</h6>
                        <ul class="list-unstyled">
                            <li> <a href="#">Dell</a></li>
                            <li> <a href="#">Asus</a></li>
                            <li> <a href="#">Apple</a></li>
                            <li> <a href="#">Microsoft</a></li>
                            <li> <a href="#">Acer</a></li>
                            <li> <a href="#">Lenlovo</a></li>
                            <li> <a href="#">Razer</a></li>
                            <li> <a href="#">HP</a></li>
                        </ul>
                    </aside>
                    <aside class="col-md col-6">
                        <h6 class="title">Liên Hệ</h6>
                        <ul class="list-unstyled">
                            <li> <a href="#">Thongdz249@gmail.com</a></li>
                            <li> <a href="#">Facebook</a></li>
                            <li> <a href="#">Instagram</a></li>
                            <li> <a href="#">Zalo</a></li>
                            <li> <a href="#">What's app</a></li>
                        </ul>
                    </aside>
                    <aside class="col-md col-6">
                        <h6 class="title">Giúp đỡ</h6>
                        <ul class="list-unstyled">
                            <li> <a href="#">Mr.Thong</a></li>
                            <li> <a href="#">thongdz249@gmail.com</a></li>

                        </ul>
                    </aside>
                    <aside class="col-md col-6">
                        <h6 class="title">Tài Khoản</h6>
                        <ul class="list-unstyled">
                            <li> <a href="#"> Login </a></li>
                            <li> <a href="#"> Đăng kí </a></li>

                        </ul>
                    </aside>
                    <aside class="col-md">
                        <h6 class="title">Mạng xã hội</h6>
                        <ul class="list-unstyled">
                            <li><a href="#"> <i class="fab fa-facebook"></i> Facebook </a></li>
                            <li><a href="#"> <i class="fab fa-twitter"></i> Twitter </a></li>
                            <li><a href="#"> <i class="fab fa-instagram"></i> Instagram </a></li>
                            <li><a href="#"> <i class="fab fa-youtube"></i> Youtube </a></li>
                        </ul>
                    </aside>
                </div> <!-- row.// -->
            </section>	<!-- footer-top.// -->

            <section class="footer-bottom text-center">

                <p class="text-white">Liên hệ thongdz249@gmail.com</p>
                <p class="text-muted">2022 </p>
                <br>
            </section>
        </div><!-- //container -->
    </footer>
    <!-- ========================= FOOTER END // ========================= -->

    <script src="~/Scripts/ckeditor/ckeditor.js"></script>

</body>
</html>