WebBanHang/WebBanHang/Areas/Admin/Controllers/AdminThongKeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHang.Context;
using WebBanHang.Models;
using PagedList.Mvc;
using PagedList;
using static WebBanHang.Common;
using System.Data;

namespace WebBanHang.Areas.Admin.Controllers
{

    public class AdminThongKeController : Controller
    {
        TNSTOREEntities db = new TNSTOREEntities();
        // GET: Admin/AdminThongKe
        public ActionResult Index(DateTime? start, DateTime? end)
        { 
            Order_OrderDetailModel model = new Order_OrderDetailModel();
            //-----//

            //version end
            ViewBag.DoanhThu = DoanhThu();
            var query = db.OrderDetails.GroupBy(a => a.SanPham).Select(a => new { soluong = a.Sum(b => b.Quantity), name = a.Key }).ToList();//lấy số lượng theo sản phẩm
            ViewBag.tongSanPham = query.Sum(n => n.soluong);// tổng số sản phẩm
            var lstSanPham = query.OrderByDescending(n => n.soluong).ToList();// sắp xếp sản phẩm theo số lượng
            model.ListOrder = db.Orders.Where(a => a.CreatedOnUtc >= start && a.CreatedOnUtc <= end).ToList();//đơn hàng theo khoảng thời gian
            var sanPhamBanChay = lstSanPham.FirstOrDefault();// sản phẩm có số lượng đặt nhiều nhất
            ViewBag.slbc = sanPhamBanChay.soluong;//số lượng sản phẩm bán chạy nhất
            var lstSpMax = from kq in lstSanPham where kq.soluong == sanPhamBanChay.soluong select kq.name;//sắp xếp các tên có cùng số lượng max
            ViewBag.lstSpMax = lstSpMax.ToList();

            model.ListOrderDetail = db.OrderDetails.Where(a => a.NgayDatHang <= end && a.NgayDatHang >= start).ToList();//chi tiết các sản phẩm dược đặt trong khoảng thời gian
            var sanphamtheongay = model.ListOrderDetail.GroupBy(a => a.SanPham).Select(a => new { soluong = a.Sum(b => b.Quantity), name = a.Key }).ToList();
            var count = sanphamtheongay.Count;
            if (count != 0)
            {
                var Sort = sanphamtheongay.OrderByDescending(n => n.soluong).ToList();// sắp xếp danh sách sản phẩm theo số lượng
                ViewBag.slOfSP = Sort.FirstOrDefault().soluong;
                var SortSl = Sort.FirstOrDefault().soluong;
                var SortMax = from sp in Sort where sp.soluong == Sort.FirstOrDefault().soluong select sp.name;
                ViewBag.SortMax = SortMax.ToList();
            }
            //Danh sách đơn hàng đã thanh toán
            model.lstDonHang = db.Orders.Where(n => n.CreatedOnUtc <= end && n.CreatedOnUtc >= start && n.Status == 2).ToList();
            ViewBag.OrderDone = model.lstDonHang.Count;
            ViewBag.sosp = model.ListOrderDetail.Sum(n => n.Quantity);//số sản phẩm

            ViewBag.sumTien = model.ListOrderDetail.Sum(n => n.Quantity * n.DonGia);// Tiền sản phẩm bán theo ngày
            ViewBag.sodh = model.ListOrder.Count;
            // sản phảm đã thanh toaqns
            model.DaThanhToan = (from a in model.lstDonHang join b in model.ListOrderDetail on a.Id equals b.OrderId select b).ToList();
            ViewBag.soluong = Sodonhang();
            ViewBag.songuoidung = Songuoidung();

            ViewBag.start = start;
            ViewBag.end = end;

            ViewBag.DoanhThuTheoThang = DoanhThuTheoThang(start, end);
            return View(model);

        }
        public decimal DoanhThu()
        {
            decimal tongDoanhThu = (decimal)db.OrderDetails.Sum(n => n.DonGia * n.Quantity).Value;
            return tongDoanhThu;

        }
        public decimal DoanhThuTheoThang(DateTime? start, DateTime? end)
        {
            var lstDonHang = db.Orders.Where(n => n.CreatedOnUtc <= end && n.CreatedOnUtc >=  start && n.Status == 2);
            decimal Money = 0;
            foreach (var item in lstDonHang)
            {
                Money += decimal.Parse(item.OrderDetails.Sum(n => n.DonGia * n.Quantity).Value.ToString());
            }
            return Money;

        }
      public decimal sumMoney() {
            
                var lstDonHang = db.Orders.Where(n => n.Status == 2);
                decimal Money = 0;
                foreach (var item in lstDonHang)
                {
                    Money += decimal.Parse(item.OrderDetails.Sum(n => n.DonGia * n.Quantity).Value.ToString());
                }
                return Money;
            
        }
        public int Sodonhang()
        {
            var soluong = db.Orders.Where(a => a.Status ==2).ToList().Count();
            return soluong;
        }
        public int Songuoidung()
        {
            var soluong = db.Users.ToList().Count();
            return soluong;
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (db != null)

                    db.Dispose();
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebBanHang/WebBanHang/Areas/Admin/Views/AdminThongKe/Index.cshtml
@model WebBanHang.Models.Order_OrderDetailModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="row" style="background-color: #000000; height: 50px; color:white; text-align:center">
    <h5 style="text-align: center; margin: 0 auto; line-height: 50px">Thống kê </h5>
</div>
<style>
    select {
        width: 660px;
        border-color: cadetblue;
        border-radius: 5px;
        border-style: inset;
        padding: 4px 4px;
    }
</style>
<table class="table table-bordered">
    <tr>
        <th>Tên sản phẩm bán chạy nhất</th>
    </tr>
    @foreach (var sp in ViewBag.lstSpMax)
    {
        <tr>
            <td>
                @sp
            </td>
        </tr>
    }

</table>
<p> với số lượng : <b>@ViewBag.slbc</b> sản phẩm</p>
<div class="row">
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-info">
            <div class="inner">

                <h5>@String.Format("{0:0,0}", ViewBag.DoanhThu) VND</h5>

                <p>Tổng doanh thu</p>
            </div>
            <div class="icon">
                <i class="ion ion-bag"></i>
            </div>
            <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-success">
            <div class="inner">
                <h5>@ViewBag.tongSanPham Sản phẩm</h5>

                <p>Được đặt hàng</p>
            </div>
            <div class="icon">
                <i class="ion ion-stats-bars"></i>
            </div>
            <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-success">
            <div class="inner">
                <h5>@ViewBag.soluong</h5>

                <p>Đơn hàng</p>
            </div>
            <div class="icon">
                <i class="ion ion-stats-bars"></i>
            </div>
            <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-warning">
            <div class="inner">
                <h5>@ViewBag.songuoidung</h5>

                <p>Người dùng</p>
            </div>
            <div class="icon">
                <i class="ion ion-person-add"></i>
            </div>
            <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
</div>

<div class="row">
    @using (Html.BeginForm("Index", "AdminThongKe", FormMethod.Get))
    {
        <p>
            <input type="date" name="start" />
            đến
            <input type="date" name="end" />
            <input type="submit" value="Tìm kiếm" />
        </p>
    }
</div>
<div class="row" style="background-color: #29a6e6; height: 50px; color:white; text-align:center">
    <h4 style="text-align: center; margin: 0 auto; line-height: 50px">Thống kê các đơn hàng được đặt theo ngày đã chọn từ @ViewBag.start đến  @ViewBag.end</h4>
</div>

<div style="display:flex;">
    <div class="col-lg-3 col-6" style="margin: 100px 50px;">
        <!-- small box -->
        <div class="small-box bg-success">
            <div class="inner">
                <h5>@ViewBag.sodh đơn hàng </h5>

                <p>@String.Format("{0:0,0}", ViewBag.sumTien) VNĐ</p>
            </div>
            <div class="icon">
                <i class="ion ion-stats-bars"></i>
            </div>
            <a href="#" class="small-box-footer" id="moreinfo">Xem danh sách<i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <div class="col-lg-3 col-6" style="margin: 100px 50px;">
        <!-- small box -->
        <div class="small-box bg-info">
            <div class="inner">
                <h5>@ViewBag.sosp Sản phẩm</h5>

                <p>Được đặt hàng</p>
            </div>
            <div class="icon">
                <i class="ion ion-stats-bars"></i>
            </div>
            <a href="#" class="small-box-footer" id="more-info-2">Xem danh sách<i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <div class="col-lg-3 col-6" style="margin: 100px 50px;">
        <!-- small box -->
        <div class="small-box bg-danger">
            <div class="inner">
                <h5>@ViewBag.OrderDone đơn hàng</h5>

                <p>Đã thanh toán:  @String.Format("{0:0,0}", ViewBag.DoanhThuTheoThang) VNĐ</p>
            </div>
            <div class="icon">
                <i class="ion ion-stats-bars"></i>
            </div>
            <a href="#" class="small-box-footer" id="more-info-2">Xem danh sách<i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
</div>
<div class="row" style="background-color: #29a6e6; height: 50px; color:white; text-align:center">
    <h4 style="text-align: center; margin: 0 auto; line-height: 50px">Danh sách các sản phẩm được đặt theo ngày đã chọn từ @ViewBag.start đến  @ViewBag.end</h4>
</div>
<div style="display: flex">
    <table class="table table-bordered">
        <tr>
            <td>Các sản phẩm được đặt nhiều nhất  <b>@ViewBag.start </b>đến  <b> @ViewBag.end </b> với số lượng <b>@ViewBag.slOfSP</b> sản phẩm</td>
        </tr>

        @if (ViewBag.SortMax != null)
        {
            foreach (var item in ViewBag.SortMax)
            {
                <tr>
                    <td>

                        @item

                    </td>

                </tr>
            }
        }
    </table>
    <table class="table table-bordered" style="margin: 50px; display: none" id="table">
        <tr>
            <th>
                Tên đơn hàng
            </th>
            <th>
                Ngày đặt hàng
            </th>
            <th>
                Trạng thái
            </th>
            <th>
                <button id="btn1" class="btn btn-warning"> ẩn </button>
            </th>
        </tr>

        @foreach (var item in Model.ListOrder)
        {
            <tr>
                <td>
                    @item.Name
                </td>
                <td>
                    @item.CreatedOnUtc
                </td>
                <th>
                    @if (item.Status == 1)
                    {
                        <p style="color:black">Chờ xác nhận</p>
                    }
                    else
                    {
                        if (item.Status == 2)
                        {


                            <p style="color:green">Đã nhận hàng</p>
                        }
                        else
                        {
                            <p style="color:red">Đang giao hàng</p>
                        }

                    }

                </th>
            </tr>
        }

    </table>
    <table class="table table-bordered" style="margin: 50px; display:none" id="table-2">
            <tr>
                <th>
                    Tên sản phẩm
                </th>
                <th>
                    Số lượng
                </th>
                <th>
                    Đơn giá
                </th>
                <th>
                    Giá tiền
                </th>
                <th>
                    Ngày đặt hàng
                </th>
                <th>
                    <button id="btn2" class="btn btn-warning"> ẩn </button>
                </th>
            </tr>
            @foreach (var detai in Model.ListOrderDetail)
            {
                <tr>
                    <td>
                        @detai.SanPham
                    </td>
                    <td>
                        @detai.Quantity
                    </td>
                    <td>
                        @detai.DonGia
                    </td>
                    <td>

                        @String.Format("{0:0,0}", (detai.DonGia * detai.Quantity)) VNĐ
                    </td>
                    <td>
                        @detai.NgayDatHang
                    </td>
                </tr>
            }
        </table>
</div>

<div class="row" style="background-color: #29a6e6; height: 50px; color:white; text-align:center">
    <h4 style="text-align: center; margin: 0 auto; line-height: 50px">Danh sách các đơn hàng đã thanh toán theo ngày đã chọn từ @ViewBag.start đến  @ViewBag.end</h4>
</div>
<table class="table table-bordered">
    <tr>
        <th>
            Tên đơn hàng
        </th>
        <th>
            Trạng thái
        </th>
    </tr>
    @foreach (var item in Model.lstDonHang)
    {
        <tr>
            <td>
                @item.Name
            </td>
            <td>
                Đã thanh toán
            </td>
        </tr>
    }
</table>
<div class="row" style="background-color: #29a6e6; height: 50px; color:white; text-align:center">
    <h4 style="text-align: center; margin: 0 auto; line-height: 50px">Danh sách sản phẩm đã thanh toán  theo ngày đã chọn từ @ViewBag.start đến  @ViewBag.end</h4>
</div>
<table class="table table-bordered">
    <tr>
        <th>Tên sản phẩm</th>
        <th>Số lượng</th>
        <th>Đơn giá</th>
    </tr>
    @foreach (var item in Model.DaThanhToan)
    {
        <tr>
            <td>
                @item.SanPham
            </td>
            <td>
                @item.Quantity
            </td>
            <td>

                @String.Format("{0:0,0}", item.DonGia) VNĐ
            </td>
        </tr>
    }

</table>
<script>
    {
        document.getElementById("moreinfo").onclick = function () {
            document.getElementById("table").style.display = 'block';
        };
        document.getElementById("btn1").onclick = function () {
            document.getElementById("table").style.display = 'none';
        };
        document.getElementById("btn2").onclick = function () {
            document.getElementById("table-2").style.display = 'none';
        };
        document.getElementById("more-info-2").onclick = function () {
            document.getElementById("table-2").style.display = 'block';
        };

    }

</script>